<!DOCTYPE html>
<html><head><title>InvokeCreateConsumerLinkAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">7 references to InvokeCreateConsumerLinkAsync</div><div class="rA">Azure.Messaging.EventHubs.Tests (7)</div><div class="rG" id="Azure.Messaging.EventHubs.Tests"><div class="rF"><div class="rN">Amqp\AmqpConsumerTests.cs (7)</div>
<a href="../Amqp/AmqpConsumerTests.cs.html#644"><b>644</b>await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, &quot;&quot;, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#716"><b>716</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, null, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.InstanceOf(terminalException.GetType()), &quot;The exception should have been surfaced on the first call.&quot;);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#717"><b>717</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, &quot;&quot;, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.Nothing, &quot;The second call should not throw.&quot;);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#718"><b>718</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, &quot;fake-id&quot;, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.Nothing, &quot;The third call should not throw.&quot;);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#737"><b>737</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, &quot;fake-id&quot;, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.InstanceOf(terminalException.GetType()), &quot;The exception should have been surfaced on the first call.&quot;);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#738"><b>738</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, &quot;&quot;, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.InstanceOf(terminalException.GetType()), &quot;The exception should have been surfaced on the second call.&quot;);</a>
<a href="../Amqp/AmqpConsumerTests.cs.html#739"><b>739</b>Assert.That(async () =&gt; await mockConsumer.<i>InvokeCreateConsumerLinkAsync</i>(&quot;cg&quot;, &quot;0&quot;, null, EventPosition.Earliest, 300, null, 34, true, TimeSpan.FromSeconds(30), CancellationToken.None), Throws.InstanceOf(terminalException.GetType()), &quot;The exception should have been surfaced on the third call.&quot;);</a>
</div>
</div>
</body></html>