<!DOCTYPE html>
<html><head><title>ExpectedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">1 instantiation of ExpectedException</div><div class="rA">Azure.Core.Tests (1)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">AsyncAssertTests.cs (1)</div>
<a href="../AsyncAssertTests.cs.html#16"><b>16</b>var exception = await AsyncAssert.ThrowsAsync&lt;ExpectedException&gt;(() =&gt; throw new <i>ExpectedException</i>());</a>
</div>
</div>
<div class="rH">4 references to ExpectedException</div><div class="rA">Azure.Core.Tests (4)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">AsyncAssertTests.cs (4)</div>
<a href="../AsyncAssertTests.cs.html#16"><b>16</b><i>var</i> exception = await AsyncAssert.ThrowsAsync&lt;<i>ExpectedException</i>&gt;(() =&gt; throw new ExpectedException());</a>
<a href="../AsyncAssertTests.cs.html#26"><b>26</b>await AsyncAssert.ThrowsAsync&lt;<i>ExpectedException</i>&gt;(() =&gt; throw new Exception());</a>
<a href="../AsyncAssertTests.cs.html#41"><b>41</b>await AsyncAssert.ThrowsAsync&lt;<i>ExpectedException</i>&gt;(() =&gt; Task.CompletedTask);</a>
</div>
</div>
</body></html>