<!DOCTYPE html>
<html><head><title>ThrowsAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">6 references to ThrowsAsync</div><div class="rA">Azure.Core.Tests (4)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">AsyncAssertTests.cs (3)</div>
<a href="../../Azure.Core.Tests/AsyncAssertTests.cs.html#16"><b>16</b>var exception = await AsyncAssert.<i>ThrowsAsync</i>&lt;ExpectedException&gt;(() =&gt; throw new ExpectedException());</a>
<a href="../../Azure.Core.Tests/AsyncAssertTests.cs.html#26"><b>26</b>await AsyncAssert.<i>ThrowsAsync</i>&lt;ExpectedException&gt;(() =&gt; throw new Exception());</a>
<a href="../../Azure.Core.Tests/AsyncAssertTests.cs.html#41"><b>41</b>await AsyncAssert.<i>ThrowsAsync</i>&lt;ExpectedException&gt;(() =&gt; Task.CompletedTask);</a>
</div>
<div class="rF"><div class="rN">RetriableStreamTests.cs (1)</div>
<a href="../../Azure.Core.Tests/RetriableStreamTests.cs.html#147"><b>147</b>var exception = await AsyncAssert.<i>ThrowsAsync</i>&lt;Exception&gt;(</a>
</div>
</div>
<div class="rA">Azure.Messaging.ServiceBus.Tests (2)</div><div class="rG" id="Azure.Messaging.ServiceBus.Tests"><div class="rF"><div class="rN">Processor\ProcessorLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.ServiceBus.Tests/Processor/ProcessorLiveTests.cs.html#297"><b>297</b>ServiceBusException exception = await AsyncAssert.<i>ThrowsAsync</i>&lt;ServiceBusException&gt;(</a>
</div>
<div class="rF"><div class="rN">Processor\SessionProcessorLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.ServiceBus.Tests/Processor/SessionProcessorLiveTests.cs.html#1808"><b>1808</b>await AsyncAssert.<i>ThrowsAsync</i>&lt;ServiceBusException&gt;(async () =&gt; await client.AcceptNextSessionAsync(scope.QueueName));</a>
</div>
</div>
</body></html>