<!DOCTYPE html>
<html><head><title>_response</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 writes to _response</div><div class="rA">Azure.AI.TextAnalytics (3)</div><div class="rG" id="Azure.AI.TextAnalytics"><div class="rF"><div class="rN">AnalyzeHealthcareEntitiesOperation.cs (3)</div>
<a href="../AnalyzeHealthcareEntitiesOperation.cs.html#210"><b>210</b><i>_response</i> = update.GetRawResponse();</a>
<a href="../AnalyzeHealthcareEntitiesOperation.cs.html#255"><b>255</b><i>_response</i> = response.GetRawResponse();</a>
<a href="../AnalyzeHealthcareEntitiesOperation.cs.html#277"><b>277</b><i>_response</i> = response.GetRawResponse();</a>
</div>
</div>
<div class="rH">2 references to _response</div><div class="rA">Azure.AI.TextAnalytics (2)</div><div class="rG" id="Azure.AI.TextAnalytics"><div class="rF"><div class="rN">AnalyzeHealthcareEntitiesOperation.cs (2)</div>
<a href="../AnalyzeHealthcareEntitiesOperation.cs.html#140"><b>140</b>public override Response GetRawResponse() =&gt; <i>_response</i>;</a>
<a href="../AnalyzeHealthcareEntitiesOperation.cs.html#222"><b>222</b>_requestFailedException = await ClientCommon.CreateExceptionForFailedOperationAsync(async, _diagnostics, <i>_response</i>, update.Value.Errors)</a>
</div>
</div>
</body></html>